# Generated by Django 4.1 on 2025-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndianRestaurantItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("north_indian", "North Indian"),
                            ("south_indian", "South Indian"),
                            ("east_indian", "East Indian"),
                            ("west_indian", "West Indian"),
                            ("street_food", "Street Food"),
                            ("dessert", "Dessert"),
                            ("beverage", "Beverage"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dietary_preference",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("non_veg", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                            ("jain", "Jain Food"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "spice_level",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("medium", "Medium"),
                            ("spicy", "Spicy"),
                            ("very_spicy", "Very Spicy"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["cuisine", "name"],
            },
        ),
    ]
