# Generated by Django 4.1 on 2025-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_dailymenu_menuemployeeassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="indianrestaurantitem",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant/items/"
            ),
        ),
    ]
