# Generated by Django 5.1.6 on 2025-03-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_employee_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(default="password", max_length=100),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                ("adddress", models.TextField(max_length=100)),
                ("status", models.CharField(default="pending", max_length=100)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.indianrestaurantitem",
                    ),
                ),
            ],
        ),
    ]
